apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: chatbot
spec:
  type: ClusterIP
  selector:
    app: llm-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
